### ISSUE TITLE
Generate %license tag for the license file in %files

### ISSUE THREAD

**Issue by tradej** [devassistant/dap2rpm#4]
As of the [latest update](https://fedoraproject.org/wiki/Packaging:LicensingGuidelines#License_Text) of Fedora Guidelines, the files that contain the licensing text in a package must be denoted with the `%license` macro. Dap2rpm currently uses the `%doc` directive, in compliance with the old guidelines.

As there is currently no mechanism in the DAP packaging to differentiate general documentation from the licensing files, I will file a bug for both [dap-dap](https://github.com/devassistant/dap-dap) and [devassistant](https://github.com/devassistant/devassistant) and link them to this one.

**Comment by hroncok** [comment]
According to discussion in devassistant/devassistant#336, here is what I propose.

 * `dap2rpm -l` will allow one more optional argument `--license`/`-L` specifiing where the license is.
 * If the option is used, the routine that generates the list will remove the given file from `%doc` and move it to `%license`
 * macro `%install_assistant` will accept one positional argument that will b passed as `--license` option to `dap2rpm`

**Comment by tradej** [comment]
Okay, this is a solution I find feasible. I will update dap2rpm and request a change to Guidelines.

**Comment by hroncok** [comment]
If this is valid:

    %files -f dap-files
    %license %{assistant_path}/doc/%{shortname}/LICENSE

We don't need any extra code, we just need to put a notice to the guidelines.

**Comment by tradej** [comment]
This is not particularly valid, as the `LICENSE` file is listed twice, which is sort of against the guidelines. Moreover, if someone installs the RPM with the `--nodocs` flag, they don't get the LICENSE file at all. I deem the change in code necessary.

**Comment by hroncok** [comment]
Also note that listing the files one by one would also need the directory itself to be added as @dir I guess, otherwise the package won't own it.

**Comment by besser82** [comment]
One actually could use:  `%doc %exclude %{assistant_path}/doc/%{shortname}/LICENSE`. That will make the file being picked-up by %license, but not by the (following) recursive glob of `%doc %{assistant_path}/doc/%{shortname}/`.

**Comment by tradej** [comment]
@besser82 If I remember correctly, I tried that, and using `%exclude` caused the file not to be picked up at all in the end.

**Comment by tradej** [comment]
Solved in 379e9feca18d13520902647eb8dc438c050cdba5
